export const CHAINID_MAINNET = process.env.REACT_APP_CHAINID_MAINNET;
export const CHAINID_TESTNET = process.env.REACT_APP_CHAINID_TESTNET;
export const PROVENANCE_WALLET_COIN_TYPE = process.env.REACT_APP_PROVENANCE_WALLET_COIN_TYPE;
