export const ICON_NAMES = {
  ARROW: 'ICON::ARROW',
  CHEVRON: 'ICON::CHEVRON',
  CLOSE: 'ICON::CLOSE',
  CONNECTED: 'ICON::CONNECTED',
  DASHBOARD: 'ICON::DASHBOARD',
  MENU: 'ICON::MENU',
  PROFILE: 'ICON::PROFILE',
  PROVENANCE: 'ICON::PROVENANCE',
  QRCODE: 'ICON::QRCODE',
  TRANSACTIONS: 'ICON::TRANSACTIONS',
};
