export const ICON_NAMES = {
  ARROW: 'ICON::ARROW',
  CLOSE: 'ICON::CLOSE',
  PROVENANCE: 'ICON::PROVENANCE',
  DASHBOARD: 'ICON::DASHBOARD',
  PROFILE: 'ICON::PROFILE',
  TRANSACTIONS: 'ICON::TRANSACTIONS',
};
