export const ICON_NAMES = {
  ARROW: 'ICON::ARROW',
  CLOSE: 'ICON::CLOSE',
  PROVENANCE: 'ICON::PROVENANCE',
  DASHBOARD: 'ICON::DASHBOARD',
  PROFILE: 'ICON::PROFILE',
  TRANSACTIONS: 'ICON::TRANSACTIONS',
  MENU: 'ICON::MENU',
  QRCODE: 'ICON::QRCODE',
  CONNECTED: 'ICON::CONNECTED',
};
